// GENERATED by tools/generate_identity.py from identity.json. Do not edit by hand.
//
// Canonical Reconclave brand identity for C++/embedded targets.
// Palette tokens are provided both as 0xRRGGBB (uint32) and RGB565 (uint16).
#ifndef RECONCLAVE_IDENTITY_H
#define RECONCLAVE_IDENTITY_H

#include <cstdint>

namespace reconclave::identity {

// Brand strings.
inline constexpr char kBrandName[] = "Reconclave";
inline constexpr char kTagline[] = "Plan on the desktop. Observe in the field. Keep the evidence together.";
inline constexpr char kMascot[] = "Zeta";
inline constexpr char kUsbManufacturer[] = "Reconclave";

// Palette as 0xRRGGBB (LVGL/TFT full-colour use).
constexpr std::uint32_t kColorCanvas = 0x050a10;  // Deepest application background and display canvas.
constexpr std::uint32_t kColorAccent = 0x00cdd7;  // Primary accent / cyan. Interactive, focus, brand.
constexpr std::uint32_t kColorWarning = 0xffaa1c;  // Attention / amber. Warnings, active/destructive-adjacent state.
constexpr std::uint32_t kColorDanger = 0xff4f87;  // Failure, destructive action, or blocked unsafe state.
constexpr std::uint32_t kColorSurface = 0x0e222e;  // Base surface / panel background.
constexpr std::uint32_t kColorSurfaceRaised = 0x16303f;  // Raised surface / cards, headers, selected rows.
constexpr std::uint32_t kColorSurfaceSelected = 0x164248;  // Selected or focused surface behind foreground content.
constexpr std::uint32_t kColorBorder = 0x237670;  // Active component outline, divider, and progress track.
constexpr std::uint32_t kColorInk = 0xfff2d7;  // Primary foreground text (warm off-white).
constexpr std::uint32_t kColorInkMuted = 0xc9b896;  // Secondary text, labels, muted detail.
constexpr std::uint32_t kColorDisabled = 0x3a4552;  // Unavailable / disabled capability or node.

// Palette as RGB565 (16-bit panels, e.g. ST7735 via TFT_eSPI).
constexpr std::uint16_t kColorCanvas565 = 0x0042;
constexpr std::uint16_t kColorAccent565 = 0x067a;
constexpr std::uint16_t kColorWarning565 = 0xfd43;
constexpr std::uint16_t kColorDanger565 = 0xfa70;
constexpr std::uint16_t kColorSurface565 = 0x0905;
constexpr std::uint16_t kColorSurfaceRaised565 = 0x1187;
constexpr std::uint16_t kColorSurfaceSelected565 = 0x1209;
constexpr std::uint16_t kColorBorder565 = 0x23ae;
constexpr std::uint16_t kColorInk565 = 0xff9a;
constexpr std::uint16_t kColorInkMuted565 = 0xcdd2;
constexpr std::uint16_t kColorDisabled565 = 0x3a2a;

}  // namespace reconclave::identity

#endif  // RECONCLAVE_IDENTITY_H
