name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  firmware:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          persist-credentials: false
      - run: cp config/generated_trust.ci.h src/generated_trust.h
      - run: pip install platformio
      - run: pio run
